In [250]:
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [251]:
data = pd.read_csv("../data/nova_pay_combined.csv")

In [252]:
data.head()

,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,exchange_rate_src_to_dest,device_id,new_device,ip_address,ip_country,location_mismatch,ip_risk_score,kyc_tier,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud
0,fee8542d-8ee6-4b0d-9671-c294dd08ed26,402cccc9-28de-45b3-9af7-cc5302aa1f93,2022-10-03 18:40:59.468549+00:00,US,USD,CAD,ATM,278.19,278.19,4.25,1.351351,9f292dcc-3297-4947-a260-6a1ef69041ff,False,221.78.171.180,US,False,0.123,standard,263,0.522,0,0.223,0,0,0.0,0
1,bfdb9fc1-27fe-4a85-b043-4d813d679259,67c2c6b3-ef0a-4777-a3f1-c84a851bb6ad,2022-10-03 20:39:38.468549+00:00,CA,CAD,MXN,web,208.51,154.29,4.24,12.758621,3a95b9f5-309f-4684-a46d-e2ff2435bf78,True,120.12.20.29,CA,False,0.569,standard,947,0.475,0,0.268,0,1,0.0,0
2,fc855034-3ea5-4993-9afa-b511d93fe5e8,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,2022-10-03 23:02:43.468549+00:00,US,USD,CNY,mobile,160.33,160.33,2.70,7.142857,a4737752-9aac-43ed-9d8b-2ccdffc24052,False,223.96.181.93,US,False,0.437,enhanced,367,0.939,0,0.176,0,0,0.0,0
3,2cf8c08e-42ec-444d-a755-34b9a2a0a4ca,7bd5200c-5d19-44f0-9afe-8b339a05366b,2022-10-04 01:08:53.468549+00:00,US,USD,EUR,mobile,59.41,59.41,2.22,0.925926,6aeb85a3-5603-4221-896c-9e6882764f1a,False,186.228.15.74,US,False,0.594,standard,147,0.551,0,0.391,0,0,0.0,0
4,d907a74d-b426-438d-97eb-dbe911aca91c,70a93d26-8e3a-4179-900c-a4a7a74d08e5,2022-10-04 09:35:03.468549+00:00,US,USD,INR,mobile,200.96,200.96,3.61,83.333333,a5b9250e-dbe0-4c5f-a6e7-5492b7349402,False,11.82.47.62,US,False,0.121,enhanced,257,0.894,0,0.257,0,0,0.0,0


In [254]:
data.shape

(11400, 26)

In [255]:
data.value_counts(data['is_fraud'])

is_fraud
0    10403
1      997
Name: count, dtype: int64

In [256]:
pd.reset_option('display.max_rows')


In [257]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 11400 entries, 0 to 11399
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   transaction_id             11400 non-null  str    
 1   customer_id                11400 non-null  str    
 2   timestamp                  11371 non-null  str    
 3   home_country               11400 non-null  str    
 4   source_currency            11400 non-null  str    
 5   dest_currency              11400 non-null  str    
 6   channel                    11400 non-null  str    
 7   amount_src                 11400 non-null  str    
 8   amount_usd                 11095 non-null  float64
 9   fee                        11105 non-null  float64
 10  exchange_rate_src_to_dest  11400 non-null  float64
 11  device_id                  11400 non-null  str    
 12  new_device                 11400 non-null  bool   
 13  ip_address                 11095 non-null  str    
 14  i

In [258]:
data['timestamp']

0        2022-10-03 18:40:59.468549+00:00
1        2022-10-03 20:39:38.468549+00:00
2        2022-10-03 23:02:43.468549+00:00
3        2022-10-04 01:08:53.468549+00:00
4        2022-10-04 09:35:03.468549+00:00
                       ...               
11395    2025-11-25 10:05:35.573611+00:00
11396    2025-11-26 07:09:56.573611+00:00
11397    2025-11-27 06:19:11.573611+00:00
11398    2025-11-28 00:53:28.573611+00:00
11399    2025-11-29 20:10:47.573611+00:00
Name: timestamp, Length: 11400, dtype: str

In [154]:
# convert timestamp to date time - done
# convert amount_src to date time 
# dropping identifiers
# drop emails
# deal with missing values
# deal with duplicates
# fix home country to be consistent with country code
# fix kyc_status to be consistent with kyc_status

In [259]:
data.isnull().mean()

transaction_id               0.000000
customer_id                  0.000000
timestamp                    0.002544
home_country                 0.000000
source_currency              0.000000
dest_currency                0.000000
channel                      0.000000
amount_src                   0.000000
amount_usd                   0.026754
fee                          0.025877
exchange_rate_src_to_dest    0.000000
device_id                    0.000000
new_device                   0.000000
ip_address                   0.026754
ip_country                   0.026404
location_mismatch            0.000000
ip_risk_score                0.000000
kyc_tier                     0.026316
account_age_days             0.000000
device_trust_score           0.025877
chargeback_history_count     0.000000
risk_score_internal          0.000000
txn_velocity_1h              0.000000
txn_velocity_24h             0.000000
corridor_risk                0.000000
is_fraud                     0.000000
dtype: float

In [260]:
# show only columns with missing values
missing = data.isnull().sum()
missing = missing[missing > 0]

print(missing)

timestamp              29
amount_usd            305
fee                   295
ip_address            305
ip_country            301
kyc_tier              300
device_trust_score    295
dtype: int64


In [261]:
data.describe(include = ['bool', 'string'])

,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,device_id,new_device,ip_address,ip_country,location_mismatch,kyc_tier
count,11400,11400,11371,11400,11400,11400,11400,11400,11400,11400,11095,11099,11400,11100
unique,11200,1315,11141,7,3,9,12,9856,2113,2,10900,9,2,14
top,4662cb2d-21b2-4390-ba38-5a1eddebdc7c,402cccc9-28de-45b3-9af7-cc5302aa1f93,0000-00-00T00:00:00Z,US,USD,NGN,mobile,100.0,e70db499-19e1-4927-b04f-3ebfcf62e33c,False,194.179.17.152,US,False,standard
freq,2,1510,21,7940,8031,1474,6366,15,87,10047,2,6848,9548,7931


In [240]:
# convert timestamp to date time - done
# convert amount_src to numeric - done

In [262]:
data['date'] = pd.to_datetime(data['timestamp'], errors='coerce')
data['amount_src'] = pd.to_numeric(data['amount_src'], errors='coerce')

In [264]:
data[['amount_src', 'timestamp']].dtypes

amount_src    float64
timestamp         str
dtype: object

In [219]:

# dropping identifiers (transaction_id, user_id, device_id) - done
# drop emails 


In [265]:
print(data.columns)

Index(['transaction_id', 'customer_id', 'timestamp', 'home_country',
       'source_currency', 'dest_currency', 'channel', 'amount_src',
       'amount_usd', 'fee', 'exchange_rate_src_to_dest', 'device_id',
       'new_device', 'ip_address', 'ip_country', 'location_mismatch',
       'ip_risk_score', 'kyc_tier', 'account_age_days', 'device_trust_score',
       'chargeback_history_count', 'risk_score_internal', 'txn_velocity_1h',
       'txn_velocity_24h', 'corridor_risk', 'is_fraud', 'date'],
      dtype='str')


In [275]:
for col in data.select_dtypes(include=['str', 'bool']).columns.tolist():
    print(data[col].value_counts())
    print('--------------------')

timestamp
0000-00-00T00:00:00Z                21
2025/13/40 25:61:00                 10
2024-01-22 00:24:24.468549+00:00     2
2022-10-03 18:40:59.468549+00:00     1
2022-10-03 20:39:38.468549+00:00     1
                                    ..
2025-11-25 10:05:35.573611+00:00     1
2025-11-26 07:09:56.573611+00:00     1
2025-11-27 06:19:11.573611+00:00     1
2025-11-28 00:53:28.573611+00:00     1
2025-11-29 20:10:47.573611+00:00     1
Name: count, Length: 11141, dtype: int64
--------------------
home_country
US         7784
UK         2091
CA         1205
 US          68
unknown      32
 UK          13
 CA           7
Name: count, dtype: int64
--------------------
source_currency
USD    7875
GBP    2111
CAD    1214
Name: count, dtype: int64
--------------------
dest_currency
NGN    1447
INR    1304
USD    1302
CNY    1297
PHP    1290
GBP    1273
CAD    1260
EUR    1177
MXN     850
Name: count, dtype: int64
--------------------
channel
mobile       6242
web          3674
ATM           9

## Dealing with duplicates

In [267]:
data.drop_duplicates(subset=['transaction_id', 'customer_id', 'device_id'], inplace=True)

In [274]:
data.duplicated().sum()

np.int64(0)

## Drop identifiers

In [271]:
data.drop(columns=['transaction_id', 'customer_id', 'device_id'], inplace=True)
# columns_to_drop = ["transaction_id", "user_id", "device_id", "email"]
# existing = [c for c in columns_to_drop if c in data.columns]

# df = data.drop(columns=existing)


In [272]:
print(data.columns.tolist())

['timestamp', 'home_country', 'source_currency', 'dest_currency', 'channel', 'amount_src', 'amount_usd', 'fee', 'exchange_rate_src_to_dest', 'new_device', 'ip_address', 'ip_country', 'location_mismatch', 'ip_risk_score', 'kyc_tier', 'account_age_days', 'device_trust_score', 'chargeback_history_count', 'risk_score_internal', 'txn_velocity_1h', 'txn_velocity_24h', 'corridor_risk', 'is_fraud', 'date']


### Deal with inconsistent categoriacal variable

In [ ]:
# cat_cols = data.select_dtypes(include=['object']).columns.tolist()
# for col in cat_cols:
#     data[col] = data[col].str.strip().str.lower()

In [280]:
for col in data.select_dtypes(include=['object']).columns.tolist():
    data[col] = data[col].str.strip().str.lower()

/tmp/ipykernel_11039/3679581355.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in data.select_dtypes(include=['object']).columns.tolist():


In [282]:
typo_corrections = {
    'channel': {'mobille': 'mobile', 'weeb': 'web'},      # Corrected typo
    'ip_country': {'nan': 'unknown'},   # Corrected typo
    'kyc_tier': {'nan': 'unknown', 'standrd': 'standard', 'enhancd': 'enhanced'},   # Corrected typo
}

for col, corrections in typo_corrections.items():
    data[col] = data[col].replace(corrections)

In [ ]:
# Check

In [283]:
for col in data.select_dtypes(include=['str', 'bool']).columns.tolist():
    print(data[col].value_counts())
    print('--------------------')

timestamp
0000-00-00t00:00:00z                21
2025/13/40 25:61:00                 10
2024-01-22 00:24:24.468549+00:00     2
2022-10-03 18:40:59.468549+00:00     1
2022-10-03 20:39:38.468549+00:00     1
                                    ..
2025-11-25 10:05:35.573611+00:00     1
2025-11-26 07:09:56.573611+00:00     1
2025-11-27 06:19:11.573611+00:00     1
2025-11-28 00:53:28.573611+00:00     1
2025-11-29 20:10:47.573611+00:00     1
Name: count, Length: 11141, dtype: int64
--------------------
home_country
us         7852
uk         2104
ca         1212
unknown      32
Name: count, dtype: int64
--------------------
source_currency
usd    7875
gbp    2111
cad    1214
Name: count, dtype: int64
--------------------
dest_currency
ngn    1447
inr    1304
usd    1302
cny    1297
php    1290
gbp    1273
cad    1260
eur    1177
mxn     850
Name: count, dtype: int64
--------------------
channel
mobile     6395
web        3766
atm        1002
unknown      37
Name: count, dtype: int64
---------

### Dealing with null values

In [284]:
data.isnull().sum()

timestamp                     29
home_country                   0
source_currency                0
dest_currency                  0
channel                        0
amount_src                     4
amount_usd                   300
fee                          290
exchange_rate_src_to_dest      0
new_device                     0
ip_address                   300
ip_country                   296
location_mismatch              0
ip_risk_score                  0
kyc_tier                     295
account_age_days               0
device_trust_score           290
chargeback_history_count       0
risk_score_internal            0
txn_velocity_1h                0
txn_velocity_24h               0
corridor_risk                  0
is_fraud                       0
date                          60
dtype: int64

In [ ]:
# Amount_usd

In [166]:
missing = df[
    ['timestamp', 'amount_usd', 'fee', 'ip_address',
     'ip_country', 'kyc_tier', 'device_trust_score']
].isnull().sum()

print(missing)

timestamp              29
amount_usd            305
fee                   295
ip_address            305
ip_country            301
kyc_tier              300
device_trust_score    295
dtype: int64


In [167]:
# This tells us how many of those seven fields are missing within each transaction.
# That one check will help us determine whether we're dealing with:

# A. scattered/random missing values, or
# B. a group of transactions where several important fields are missing together.

# For a fraud detection project, I strongly prefer figuring that out first because missingness itself can potentially be a useful fraud signal.

In [168]:
df[['timestamp', 'amount_usd', 'fee', 'ip_address',
   'ip_country', 'kyc_tier', 'device_trust_score']].isnull().sum(axis=1).value_counts()

0    11066
6      290
1       29
4       14
5        1
Name: count, dtype: int64

In [169]:
# So out of 11,400 transactions, you have:

# 11,066 (97.1%) with no missing values among these seven variables.
# 290 transactions missing 6 out of 7 fields.
# 14 transactions missing 4 fields.
# 1 transaction missing 5 fields.
# 29 transactions missing just 1 field.

In [170]:
# Find which field is NOT missing
# This will show us the 290 transactions where 6 of the 7 fields are missing.

# I'm particularly interested in which variable remains populated.

In [171]:
cols = [
    'timestamp',
    'amount_usd',
    'fee',
    'ip_address',
    'ip_country',
    'kyc_tier',
    'device_trust_score'
]

df[df[cols].isnull().sum(axis=1) == 6][cols]

,timestamp,amount_usd,fee,ip_address,ip_country,kyc_tier,device_trust_score
13,2022-10-05 07:04:39.468549+00:00,NaN,NaN,NaN,NaN,NaN,NaN
49,2022-10-08 20:45:48.468549+00:00,NaN,NaN,NaN,NaN,NaN,NaN
151,2022-10-20 22:08:59.468549+00:00,NaN,NaN,NaN,NaN,NaN,NaN
163,2022-10-22 01:51:23.468549+00:00,NaN,NaN,NaN,NaN,NaN,NaN
168,2022-10-22 10:08:19.468549+00:00,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
10054,2025-06-20 07:38:53.468549+00:00,NaN,NaN,NaN,NaN,NaN,NaN
10082,2025-01-27 17:14:38.468549+00:00,NaN,NaN,NaN,NaN,NaN,NaN
10093,2024-06-28 06:10:20.468549+00:00,NaN,NaN,NaN,NaN,NaN,NaN
10142,2024-03-04 21:11:40.468549+00:00,NaN,NaN,NaN,NaN,NaN,NaN


In [172]:
# Lets investigate these records across 'is_fraud' column

In [173]:
incomplete = df[cols].isnull().sum(axis=1) == 6

print("Incomplete transactions:", incomplete.sum())

print("\nFraud rate among incomplete:")
print(df.loc[incomplete, 'is_fraud'].mean())

print("\nFraud rate among other transactions:")
print(df.loc[~incomplete, 'is_fraud'].mean())

Incomplete transactions: 290

Fraud rate among incomplete:
0.027586206896551724

Fraud rate among other transactions:
0.08901890189018902


In [174]:
# “Among rows that are not missing most of the important fields, what fraction are fraud?”

In [175]:
df.columns

Index(['transaction_id', 'timestamp', 'home_country', 'source_currency',
       'dest_currency', 'channel', 'amount_src', 'amount_usd', 'fee',
       'exchange_rate_src_to_dest', 'new_device', 'ip_address', 'ip_country',
       'location_mismatch', 'ip_risk_score', 'kyc_tier', 'account_age_days',
       'device_trust_score', 'chargeback_history_count', 'risk_score_internal',
       'txn_velocity_1h', 'txn_velocity_24h', 'corridor_risk', 'is_fraud',
       'date'],
      dtype='str')

In [176]:
df['amount_missing'] = df['amount_usd'].isna().astype(int)
df['fee_missing'] = df['fee'].isna().astype(int)
df['ip_missing'] = df['ip_address'].isna().astype(int)
df['kyc_missing'] = df['kyc_tier'].isna().astype(int)
df['device_trust_missing'] = df['device_trust_score'].isna().astype(int)

In [177]:
# I considered creating missingness indicators, particularly for the variables where missingness may have meaning.
# This transaction didn't have an amount recorded. rather than us simply hiding that fact through imputation.

In [178]:
incomplete = df[cols].isnull().sum(axis=1) == 6

print(df.loc[incomplete, 'timestamp'].min())
print(df.loc[incomplete, 'timestamp'].max())

2022-10-05 07:04:39.468549+00:00
2025-09-25 04:13:25.468549+00:00


In [179]:
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

In [180]:
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

incomplete = df[cols].isnull().sum(axis=1) == 6

result = df.loc[incomplete, 'timestamp'].dt.year.value_counts().sort_index()
print(result)

timestamp
2022    27
2023    92
2024    88
2025    83
Name: count, dtype: int64


In [181]:
df.loc[incomplete].describe(include='all')

,transaction_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,exchange_rate_src_to_dest,new_device,ip_address,ip_country,location_mismatch,ip_risk_score,kyc_tier,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud,date,amount_missing,fee_missing,ip_missing,kyc_missing,device_trust_missing
count,290,290,290,290,290,290,290.000000,0.0,0.0,290.000000,290,0,0,290,290.000000,0,290.000000,0.0,290.0,290.000000,290.000000,290.000000,290.000000,290.000000,290,290.0,290.0,290.0,290.0,290.0
unique,285,NaN,3,3,9,3,NaN,NaN,NaN,NaN,2,0,0,2,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,ddb073fa-05d9-45b0-90bf-7336b7ef67ff,NaN,US,USD,NGN,mobile,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2,NaN,201,201,40,187,NaN,NaN,NaN,NaN,262,NaN,NaN,261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,2024-04-06 18:24:46.451307+00:00,NaN,NaN,NaN,NaN,362.126241,NaN,NaN,170.440933,NaN,NaN,NaN,NaN,0.341028,NaN,417.875862,NaN,0.0,0.238728,0.113793,0.189655,0.043621,0.027586,2024-04-06 18:24:46.451307+00:00,1.0,1.0,1.0,1.0,1.0
min,NaN,2022-10-05 07:04:39.468549+00:00,NaN,NaN,NaN,NaN,15.460000,NaN,NaN,0.592000,NaN,NaN,NaN,NaN,0.014000,NaN,4.000000,NaN,0.0,0.029000,0.000000,0.000000,0.000000,0.000000,2022-10-05 07:04:39.468549+00:00,1.0,1.0,1.0,1.0,1.0
25%,NaN,2023-07-07 13:57:41.968549+00:00,NaN,NaN,NaN,NaN,83.960000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,0.192000,NaN,224.750000,NaN,0.0,0.166000,0.000000,0.000000,0.000000,0.000000,2023-07-07 13:57:41.968549+00:00,1.0,1.0,1.0,1.0,1.0
50%,NaN,2024-04-02 10:33:07.468549+00:00,NaN,NaN,NaN,NaN,158.165000,NaN,NaN,7.142857,NaN,NaN,NaN,NaN,0.307000,NaN,298.000000,NaN,0.0,0.223000,0.000000,0.000000,0.000000,0.000000,2024-04-02 10:33:07.468549+00:00,1.0,1.0,1.0,1.0,1.0
75%,NaN,2025-01-27 17:14:38.468549+00:00,NaN,NaN,NaN,NaN,287.507500,NaN,NaN,80.882353,NaN,NaN,NaN,NaN,0.445750,NaN,718.000000,NaN,0.0,0.339750,0.000000,0.000000,0.000000,0.000000,2025-01-27 17:14:38.468549+00:00,1.0,1.0,1.0,1.0,1.0
max,NaN,2025-09-25 04:13:25.468549+00:00,NaN,NaN,NaN,NaN,9998.860000,NaN,NaN,1388.888889,NaN,NaN,NaN,NaN,0.991000,NaN,1074.000000,NaN,0.0,0.407000,7.000000,7.000000,0.250000,1.000000,2025-09-25 04:13:25.468549+00:00,1.0,1.0,1.0,1.0,1.0


In [182]:
df.loc[incomplete].head()

,transaction_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,exchange_rate_src_to_dest,new_device,ip_address,ip_country,location_mismatch,ip_risk_score,kyc_tier,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud,date,amount_missing,fee_missing,ip_missing,kyc_missing,device_trust_missing
13,1a34a095-3be4-4a69-a22e-803be566526c,2022-10-05 07:04:39.468549+00:00,UK,GBP,EUR,mobile,322.24,NaN,NaN,1.157407,False,NaN,NaN,False,0.245,NaN,4,NaN,0,0.407,0,0,0.05,0,2022-10-05 07:04:39.468549+00:00,1,1,1,1,1
49,b489474c-b729-4759-86e9-51778ddea385,2022-10-08 20:45:48.468549+00:00,US,USD,INR,mobile,255.06,NaN,NaN,83.333333,False,NaN,NaN,False,0.530,NaN,263,NaN,0,0.223,0,0,0.00,0,2022-10-08 20:45:48.468549+00:00,1,1,1,1,1
151,32cbd613-5c6c-4797-be15-165bc408c2ca,2022-10-20 22:08:59.468549+00:00,US,USD,MXN,mobile,502.97,NaN,NaN,17.241379,False,NaN,NaN,False,0.310,NaN,1018,NaN,0,0.087,0,0,0.20,0,2022-10-20 22:08:59.468549+00:00,1,1,1,1,1
163,8b339135-7446-4689-9bd2-0509f23903f0,2022-10-22 01:51:23.468549+00:00,CA,CAD,USD,web,100.87,NaN,NaN,0.740000,False,NaN,NaN,False,0.519,NaN,947,NaN,0,0.268,7,7,0.00,0,2022-10-22 01:51:23.468549+00:00,1,1,1,1,1
168,c6c7f296-be97-4d18-a93e-719fcba43dce,2022-10-22 10:08:19.468549+00:00,US,USD,MXN,mobile,265.30,NaN,NaN,17.241379,False,NaN,NaN,True,0.655,NaN,367,NaN,0,0.176,0,0,0.20,0,2022-10-22 10:08:19.468549+00:00,1,1,1,1,1


In [183]:
"""Timestamp:
Only 29 are missing, and timestamp is fundamental to fraud analysis. I would rather lose 29 records than invent dates that could distort temporal patterns.

Amount and fee:
They're numerical. Median is safer than mean because transaction amounts can be heavily skewed. The missing indicators preserve the information that the original value was missing.

IP address, country and KYC tier:
Don't invent these values. "Unknown" is a legitimate category and allows the model to potentially learn whether missing information is associated with fraud.

Device trust score:
Use the median, but retain a device_trust_missing flag because the absence of a score may itself contain information.
And those 290 records?

Keep them
They represent only about 2.54% of your data, and we've established that their fraud rate is actually lower (2.76%) than the rest (8.90%). There's no good reason to throw them away simply because they're incomplete.
The missingness pattern should be documented, but we don't need to spend another ten steps investigating it unless your project specifically requires a missing-data mechanism analysis."""

'Timestamp:\nOnly 29 are missing, and timestamp is fundamental to fraud analysis. I would rather lose 29 records than invent dates that could distort temporal patterns.\n\nAmount and fee:\nThey\'re numerical. Median is safer than mean because transaction amounts can be heavily skewed. The missing indicators preserve the information that the original value was missing.\n\nIP address, country and KYC tier:\nDon\'t invent these values. "Unknown" is a legitimate category and allows the model to potentially learn whether missing information is associated with fraud.\n\nDevice trust score:\nUse the median, but retain a device_trust_missing flag because the absence of a score may itself contain information.\nAnd those 290 records?\n\nKeep them\nThey represent only about 2.54% of your data, and we\'ve established that their fraud rate is actually lower (2.76%) than the rest (8.90%). There\'s no good reason to throw them away simply because they\'re incomplete.\nThe missingness pattern should b

"""Timestamp:
Only 29 are missing, and timestamp is fundamental to fraud analysis. I would rather lose 29 records than invent dates that could distort temporal patterns.

Amount and fee:
They're numerical. Median is safer than mean because transaction amounts can be heavily skewed. The missing indicators preserve the information that the original value was missing.

IP address, country and KYC tier:
Don't invent these values. "Unknown" is a legitimate category and allows the model to potentially learn whether missing information is associated with fraud.

Device trust score:
Use the median, but retain a device_trust_missing flag because the absence of a score may itself contain information.

And those 290 records?

Keep them.

They represent only about 2.54% of your data, and we've established that their fraud rate is actually lower (2.76%) than the rest (8.90%). There's no good reason to throw them away simply because they're incomplete.

The missingness pattern should be documented, but we don't need to spend another ten steps investigating it unless your project specifically requires a missing-data mechanism analysis."""

In [184]:

# deal with duplicates
# fix home country to be consistent with country code
# fix kyc_status to be consistent with kyc_status

In [185]:
# 2. Remove rows where timestamp is missing
df = df.dropna(subset=['timestamp'])

In [186]:
# 3. Create missingness indicators for numerical variables
df['amount_missing'] = df['amount_usd'].isna().astype(int)
df['fee_missing'] = df['fee'].isna().astype(int)
df['device_trust_missing'] = df['device_trust_score'].isna().astype(int)

In [187]:
# 4. Median imputation for numerical variables
df['amount_usd'] = df['amount_usd'].fillna(df['amount_usd'].median())
df['fee'] = df['fee'].fillna(df['fee'].median())
df['device_trust_score'] = df['device_trust_score'].fillna(
    df['device_trust_score'].median()
)

In [188]:
# 5. Fill categorical/text variables
df['ip_address'] = df['ip_address'].fillna('Unknown')
df['ip_country'] = df['ip_country'].fillna('Unknown')
df['kyc_tier'] = df['kyc_tier'].fillna('Unknown')

In [189]:
# Dealing with Duplicates

In [190]:
df.duplicated().sum()

np.int64(199)

In [191]:
df.duplicated(subset=['transaction_id']).sum()

np.int64(199)

In [192]:
df.columns.tolist()

['transaction_id',
 'timestamp',
 'home_country',
 'source_currency',
 'dest_currency',
 'channel',
 'amount_src',
 'amount_usd',
 'fee',
 'exchange_rate_src_to_dest',
 'new_device',
 'ip_address',
 'ip_country',
 'location_mismatch',
 'ip_risk_score',
 'kyc_tier',
 'account_age_days',
 'device_trust_score',
 'chargeback_history_count',
 'risk_score_internal',
 'txn_velocity_1h',
 'txn_velocity_24h',
 'corridor_risk',
 'is_fraud',
 'date',
 'amount_missing',
 'fee_missing',
 'ip_missing',
 'kyc_missing',
 'device_trust_missing']

In [193]:
df.dtypes

transaction_id                               str
timestamp                    datetime64[us, UTC]
home_country                                 str
source_currency                              str
dest_currency                                str
channel                                      str
amount_src                               float64
amount_usd                               float64
fee                                      float64
exchange_rate_src_to_dest                float64
new_device                                  bool
ip_address                                   str
ip_country                                   str
location_mismatch                           bool
ip_risk_score                            float64
kyc_tier                                     str
account_age_days                           int64
device_trust_score                       float64
chargeback_history_count                   int64
risk_score_internal                      float64
txn_velocity_1h     

In [194]:
df[['amount_usd', 'fee', 'device_trust_score']].describe()

,amount_usd,fee,device_trust_score
count,11339.000000,11339.000000,11339.000000
mean,443.840485,98.281776,0.653672
std,1383.569103,948.290565,0.269611
min,7.230000,-1.000000,-0.100000
25%,94.065000,2.410000,0.515000
50%,163.645000,3.500000,0.658000
75%,295.750000,5.460000,0.894000
max,12498.570000,9999.990000,0.999000


In [ ]:
# But before changing them, let's find out how many transactions have these extreme values.

In [195]:
df[df['fee'] < 0]['fee'].value_counts()

fee
-1.0    101
Name: count, dtype: int64

In [ ]:
# I'm deliberately using 100 here as an investigation threshold, not saying that $100 is automatically an invalid fee.

In [196]:
df[df['fee'] > 100]['fee'].describe()

count     310.000000
mean     3422.781968
std      4647.046921
min       103.380000
25%       150.760000
50%       151.305000
75%      9999.990000
max      9999.990000
Name: fee, dtype: float64

In [ ]:
# Let's find out how many values are outside the expected range:

In [197]:
df[
    (df['device_trust_score'] < 0) |
    (df['device_trust_score'] > 1)
]['device_trust_score'].value_counts()

device_trust_score
-0.1    204
Name: count, dtype: int64

In [198]:
df.shape

(11339, 30)

In [199]:
df[['amount_usd', 'fee', 'device_trust_score']].isna().sum()

amount_usd            0
fee                   0
device_trust_score    0
dtype: int64

In [200]:
df[df['fee'] < 0]['fee'].value_counts()

fee
-1.0    101
Name: count, dtype: int64

In [201]:
df[
    (df['device_trust_score'] < 0) |
    (df['device_trust_score'] > 1)
]['device_trust_score'].value_counts()

device_trust_score
-0.1    204
Name: count, dtype: int64

In [ ]:
df.columns.tolist()
df.shape